
server.port=8080
spring.application.name=API-GATEWAY
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${spring.application.name}:${server.port}
# AUTH FIRST
spring.cloud.gateway.routes[0].id=auth-route
spring.cloud.gateway.routes[0].uri=lb://TASK-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/tasks/api/v1/auth/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# TASK SECOND
spring.cloud.gateway.routes[1].id=task-service
spring.cloud.gateway.routes[1].uri=lb://TASK-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/tasks/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1
# NOTIFICATION
spring.cloud.gateway.routes[2].id=notification-service
spring.cloud.gateway.routes[2].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/notify/**

# Admin Server
#spring.boot.admin.client.url=http://localhost:9090

# Actuator - Open for Admin Server
management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=always