spring.application.name=ADMIN-SERVER
server.port=9090
management.endpoints.jackson.isolated-object-mapper=false
# Eureka client configuration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
# Admin Server discovery
spring.boot.admin.discovery.enabled=true
spring.boot.admin.discovery.services=*
# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
# Force Spring Boot Admin UI
spring.boot.admin.ui.enabled=true
spring.boot.admin.ui.cache.no-cache=false
spring.boot.admin.ui.extension-resource-locations=classpath:/META-INF/spring-boot-admin-server-ui/extensions/
spring.boot.admin.ui.cache-templates=false

# WebFlux static resource handling
spring.webflux.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/META-INF/spring-boot-admin-server-ui/